version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: futurenews-backend
    environment:
      - secret=${JWT_SECRET}
      - algorithm=${JWT_ALGORITHM}
      - openai_api_key=${OPENAI_API_KEY}
      - news_api_key=${NEWS_API_KEY}
      - media_stack_api_key=${MEDIA_STACK_API_KEY}
    ports:
      - "8081:8081"
    volumes:
      - sqlite_data:/app/data
    networks:
      - futurenews-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8081  # Using service name instead of localhost
    container_name: futurenews-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - futurenews-network

networks:
  futurenews-network:
    driver: bridge

volumes:
  sqlite_data: